### PR TITLE
Update documentation and add all required permissions to policy

### PR DESCRIPTION
**Pull request by patrick-gleeson**
Thanks for making some great improvements to @xombiemp's excellent work. I had a go at setting this up for myself just now, and came across two minor issues I thought would be worth correcting:

- The first is that the UI for creating Lambdas has changed slightly, so I've updated the `Create Lambda function` section in the readme to match.
- The second is that when I tested the function I got complaints about permission being denied until I added a couple more actions to the IAM policy. I've added the new actions to the JSON file.

I'm submitting these to help other people who your fork and want to get going with it.

### CODE REVIEW

**Comment by tamalerhino** [comment]
@patrick-gleeson  did you have any issues when setting` INSTANCES = ["all"],` ? it errors out on me, it works fine when i give it a database name though.

**Comment by patrick-gleeson** [comment]
@chito4 I never tried using the 'all' setting I'm afraid.

**Comment by swmacdonald** [comment]
Looks good, thanks for contributing.  Hope you found the function useful!

**Comment by blackwith** [comment]
Very nice script 👍  but unfortunately it doesn't work anymore, i don't understand why...
I know this not the good place to tell this but issue tab isn't existing.

here the error :
  File "/var/task/rds-copy-snapshots-lambda_monthly.py", line 124, in main
    NOW = parser.parse(event['time'])
KeyError: 'time'

**Comment by patrick-gleeson** [comment]
Hi @blackwith, that's not a problem with the script, it's a problem with how you're using it 😄 .

The script has to be triggered by a Cloudwatch Event (or, for testing, by a Scheduled Event). If that sort of event is used as a trigger, then there will indeed be a 'time' key in the event hash and you won't get a KeyError. If you're using a different type of event to trigger the script you may get that error.

**Comment by blackwith** [comment]
Yes it's works fine, my apologize. I misread or I dont know read (make your choice). 
Thanks very much for your answer and thanks a lot for your script.

**Pull request merged**
